### ISSUE TITLE
Clean up readme

### ISSUE THREAD

**Issue by chrisgervang** [Turfjs/turf-vincenty-direct#3]
Wanted to compile together a few typos in the docs.

I don't believe `turf.vincenty-direct` is a valid javascript function name, and `vincenty-direct` (or vincentyDirect) aren't exported from the main `@turf/turf` package. So this should probably be reworded?

The docs use `destination` (haversine) function.. it should probably be a `vincenty` function that comes in from an import statement.

**Comment by DenisCarriere** [comment]
This module has not yet made it to Turf's mono repo.

Please move this issue to the main Turf repo.
